name: Java CI with Maven and Deploy to Repository

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 17 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.4.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          architecture: x64

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "vouncherstudios-repository-snapshots",
                "username": "${{ secrets.REPOSITORY_USERNAME }}",
                "password": "${{ secrets.REPOSITORY_PASSWORD }}"
            }]

      - name: Build and Deploy
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          ./acf deploy