name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 17 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.4.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          architecture: x64

      - name: Build
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          ./acf build